### ISSUE TITLE
Raise only working for tiled windows

### ISSUE THREAD

**Issue by dag-h** [conformal/spectrwm#386] opened 2020-09-19 14:59 UTC
Raise doesn't seem to work for floating windows, only raises tiled windows above floating ones. This makes it very difficult to work with multiple floating windows. I'm guessing this is unintended behavior?

**Comment by wavexx** [comment] 2021-01-24 19:52
Noticed this as well. It used to work correctly, but regressed at some point

**Comment by wavexx** [comment] 2021-01-28 14:30
I might have spoken too soon. I cannot reproduce this one on the current master.
@Harjuu do you have some way to reproduce this issue?

**Comment by Harjuu** [comment] 2021-02-08 10:46
@wavexx Sorry for the late reply. This seems to have been fixed, as I can't currently reproduce this either. Closing unless someone else feels like this is reproducable somehow.

**Closed** 2023-01-21 04:28 UTC
Labels: bug
