### ISSUE TITLE
Missing input and abnormal behavior for +W format on ws with iconified window after ws switching

### ISSUE THREAD

**Issue by osimplex** [conformal/spectrwm#369] opened 2020-07-05 04:05 UTC
Steps:
1. I'm on ws 7, that is clear, then open a window, then iconify it;
2. Go to a ws where there is _something open_, like Firefox, or Zathura;
3. Return to ws 7, where is the iconified window;
4. Get the abnormal behavior:
4.1. The bar has the title of the last iconified window, instead of of nothing for `+W` position of `bar_format`;
4.2. The input is missing, so I cannot use any binding of spectrwm or an external hk daemon like sxhkd.
5. The strange behavior ends when I click anywhere, except the panel (tested with builtin panel).

If, in step `2`, the ws that I go to is clear, I only get the abnormal behavior `4.1`, input works as expected.

Distro: Arch Linux
spectrwm version: 3.4.1-1

**Comment by LordReg** [comment] 2020-09-16 09:31
I was unable to reproduce 4.2 but the issue should now be fixed in master.   Please reopen if not.

**Closed by LordReg** 2020-09-16 09:31 UTC
Labels: bug
