### ISSUE TITLE
spectrwm frequently loses input/focus

### ISSUE THREAD

**Issue by mewa** [conformal/spectrwm#244] opened 2019-02-14 10:54 UTC
I'm experiencing a couple hangs on a daily basis, sometimes several within a short timespan.

I'm not sure if it's related to #192  though, since I cannot restart anything with `mod+q`, as `spectrwm` loses all input (it works if I kill just `spectrwm`). Mouse movement is also possible (without clicking).

I think it might be related to focus handling, since sometimes when I see this issue occur (unable to switch, but somehow retaining my current focus) I can still type in currently focused window. Then if I try to switch windows it seems to lose focus (although visual indicator says otherwise) and stops responding to key/mouse presses.

I have experienced this on several builds, including when building from `master` (as I far as I can tell there was an infinite loop fix recently).
OS: archlinux

Some logs:
```
4423 event_handle: PropertyNotify(28), seq 22940
4423 propertynotify: win 0xe00016, atom: (null)(406), time: 0x5286a8, state: 0
4423 find_window: id: 0xe00016
4423 event_handle: PropertyNotify(28), seq 22947
4423 propertynotify: win 0xe00016, atom: (null)(406), time: 0x528750, state: 0
4423 find_window: id: 0xe00016
4423 event_handle: PropertyNotify(28), seq 22954
4423 propertynotify: win 0xe00016, atom: (null)(406), time: 0x528920, state: 0
4423 find_window: id: 0xe00016
4423 event_handle: PropertyNotify(28), seq 22961
4423 propertynotify: win 0xe00016, atom: (null)(406), time: 0x528988, state: 0
4423 find_window: id: 0xe00016
4423 event_handle: PropertyNotify(28), seq 22968
4423 propertynotify: win 0xe00016, atom: (null)(406), time: 0x528a28, state: 0
4423 find_window: id: 0xe00016
4424 event_handle: PropertyNotify(28), seq 22975
4424 propertynotify: win 0xe00016, atom: (null)(406), time: 0x528a80, state: 0
4424 find_window: id: 0xe00016
4440 event_handle: PropertyNotify(28), seq 23087
4440 propertynotify: win 0xe00016, atom: (null)(406), time: 0x52c8d0, state: 0
4440 find_window: id: 0xe00016
4440 event_handle: PropertyNotify(28), seq 23094
4440 propertynotify: win 0xe00016, atom: (null)(406), time: 0x52ca80, state: 0
4440 find_window: id: 0xe00016
4440 event_handle: PropertyNotify(28), seq 23101
4440 propertynotify: win 0xe00016, atom: (null)(406), time: 0x52cb30, state: 0
4440 find_window: id: 0xe00016
4440 event_handle: PropertyNotify(28), seq 23108
4440 propertynotify: win 0xe00016, atom: (null)(406), time: 0x52cc60, state: 0
4440 find_window: id: 0xe00016
[9084:9084:0214/123721.848785:ERROR:latency_info.cc(147)] Surface::TakeLatencyInfoFromFrame, LatencyInfo vector size 101 is too big.
[9084:9084:0214/124052.840175:ERROR:latency_info.cc(147)] Surface::TakeLatencyInfoFromFrame, LatencyInfo vector size 101 is too big.
[9084:9084:0214/124105.980888:ERROR:latency_info.cc(147)] Surface::TakeLatencyInfoFromFrame, LatencyInfo vector size 102 is too big.
[9084:9084:0214/124138.840971:ERROR:latency_info.cc(147)] Surface::TakeLatencyInfoFromFrame, LatencyInfo vector size 101 is too big.
```

**Comment by mewa** [comment] 2019-03-07 10:10
I tried fixing it myself but, unfortunately, looking through code hasn't taken me far yet.

I have collected almost 180MB of logs by now, maybe tailing through it might help. I can include them if need be, maybe for someone more familiar with spectrwm the will make some more sense.

I'd really like to contribute to a fix as having to constantly reset is seriously impairing my workflow and a few hints would definitely aid in that.

**Comment by LordReg** [comment] 2019-03-07 19:30
Does this happen with any particular app(s)? Any heavy i/o when it occurs? I'm also on Arch and I sometimes experience a hang as you describe during heavy disk i/o.

Those errors in your log should be unrelated to this issue.  I sometimes see them in my log too from chromium.

**Comment by mewa** [comment] 2019-03-07 22:59
Actually, I'm using chromium as well and it often freezes while using it.
On a side note, I do have a lot of tabs opened at all times. Theoretically speaking, they should already be in memory but maybe some of them are loading in the background from disk cache which could cause an i/o spike (but then again, this is just a wild guess).

However, I'm beginning to think this issue may be Xorg-related, as I have just switched to bspwm and had it happen as well (although just once, I will try to reproduce it here as well).

**Comment by LordReg** [comment] 2019-03-08 01:26
I did a bit of testing and it turns out I get the freezing when debug output is written to a busy device where the write operation gets blocked.  Probably best to direct debug output to /tmp or some other independent device.

You can reproduce the issue by duplicating a large file on the same device as spectrwm.log and running `sync` in a separate terminal.

**Comment by mewa** [comment] 2019-03-09 11:02
Does it unfreeze for you after you're done with the sync?

Also, I had it happen another couple times on bspwm.
I'll try to dig into Xorg, since it seems to be the most obvious common-denominator.

**Comment by LordReg** [comment] 2019-03-09 12:34
Yes, it always unfreezes but I've experienced getting stuck in a window move operation from stderr being blocked probably due to button/key release events being dropped while the event queue is held up.

Do you experience any freezing with SWM_DEBUG disabled?

**Comment by mewa** [comment] 2019-03-10 12:23
For me it never does.

It happens with `SWM_DEBUG` disabled too.

**Comment by mewa** [comment] 2019-03-13 10:54
@LordReg I think your diagnosis regarding busy device is correct. I don't think I'm experiencing this issue while attached to tty.

**Comment by marcopeereboom** [comment] 2019-04-11 20:35
Can this be closed?

**Comment by mewa** [comment] 2019-04-11 23:44
Well, it would be nice if we could come up with a solution that handles this issue and doesn't require any restart whatsoever.

**Comment by marcopeereboom** [comment] 2019-04-12 08:33
I am not sure this can be fixed. If X drops events spectrwm can't know or handle that.

**Comment by LordReg** [comment] 2020-02-21 10:09
@mewa Does this still occur with latest master branch?

**Comment by andou-azarashi** [comment] 2020-04-19 20:30
It happen everytime I try to open firefox that is not at 1:2. firefox will flick and jump to 1:2, then I will lose control, no input accept until I use the mouse to click on the screen.

**Comment by andou-azarashi** [comment] 2020-04-19 20:38
It happen everytime I try to open firefox that is not at 1:2. firefox will flick and jump to 1:2, then I will lose control, no input accept until I use the mouse to click on the screen.

**Comment by LordReg** [comment] 2020-06-17 09:44
Should be fixed now.

**Closed by LordReg** 2020-06-17 09:44 UTC
Labels: bug
