### ISSUE TITLE
In multiple monitor setup, menu opens in the previous region

### ISSUE THREAD

**Issue by rohshall** [conformal/spectrwm#191] opened 2017-12-27 17:41 UTC
I am using the master branch version. And I find that on Java IDE, the clicking the menu, opens it in the original region (monitor) where the IDE window was originally opened, even though the window is now in another region. I have attached the screenshot of the menu opening up in screen 1, where I first opened the IDE, and then later moved to screen 2. 
![2017-12-27-094000_3840x1200_scrot](https://user-images.githubusercontent.com/225175/34388710-1ca64be2-eaea-11e7-8fda-136e34f1b5c3.png)

**Comment by wavexx** [comment] 2018-09-12 21:16
I was finally able to pin down this odd behavior in java programs.
I can confirm there is some issue when moving java programs from one workspace to the other.

In my case (sqlworkbench, or "josm" the openstreermap editor), the main menus appear where they should, but menu items do not highlight and/or work as they should unless the pointer is moved to some position offset from where it should be. Popups or drop-downs also appear in a different spot.

In my case, I can reliably cause this mis-behavior by opening the program in one monitor (normally the second monitor) and send it to a workspace which is directly visible on the first monitor.

**Comment by a4free** [comment] 2018-09-28 15:37
@rohshall 
Hi, Mr. Wadnerkar,
I see you have two monitor and display different tasks. It's cool.
I wander how to made this. Hope 4 your reply and thx. ;-)
ps. what if the two monitor is in different resolution.

**Comment by marcopeereboom** [comment] 2020-06-01 14:38
Is this still an issue?

**Comment by wavexx** [comment] 2020-06-01 14:55
Sadly, yes.  Quickest repro I could find

- dual screen
- start with 2 windows on both regions
- run `sqlworkbench` (currently using openjre 15)
- menus seem to work
- use rg_move_next

Results in some of the menus not working (likely opening somewhere offscreen), some open as long as you keep the mouse pressed but submenu highlight doesn't work as expected (highlight appears if you move the mouse on the original screen), OR menu appears on the first screen but highlight works as if the mouse is over it.

**Comment by wavexx** [comment] 2021-01-24 20:02
To pin it down further, you don't need to have two screen/regions to reproduce it.

In a tiled layout, most java programs seem to misbehave. The menu location seems to reflect the position where the window has been mapped the first time.

Looking at the source code, there are some notes regarding java with a single operation combining a move+resize, which is exactly what happens in a tile. The problem is that "java detection" doesn't seem to trigger on these windows, and I cannot see any relevant attribute that we could match reliably.

@marcopeereboom I've seen some notes in other tiling WMs that set _NET_WM_NAME to some value which is whitelisted by java, allegedly fixing "some stuff". For example, qtile sets "LG3D".. did you ever investigate into this?

**Comment by wavexx** [comment] 2021-01-24 20:04
To add more info, it seems that all Java programs using the Swing toolkit are affected.

**Comment by LordReg** [comment] 2021-01-25 01:47
@wavexx the java window detection/workaround relies on how java (used to) prefix `WM_CLASS` *instance* field with 'sun-awt'. At some point after openjre 8, that behavior changed:

- openjre 8:
```WM_CLASS(STRING) = "sun-awt-X11-XFramePeer", "workbench-WbStarter"```

- openjre 11 & 15:
```WM_CLASS(STRING) = "workbench-WbStarter", "workbench-WbStarter"```

The issue is that java doesn't comply with ICCCM when handling ConfigureNotify from reparenting WMs, except for a select few it detects:
https://github.com/openjdk/jdk15/blob/19b8204719c50d70fa435f9484a61365258b46c3/src/java.desktop/unix/classes/sun/awt/X11/XWindowPeer.java#L772

Since it appears there is no clean way to detect java windows with newer versions of java, a new `JAVA` quirk could be introduced.. and/or maybe a command line option for the user to override _NET_WM_NAME... I'm not sure how many apps actually use that value, but I feel it would be silly to misreport the value (by default), just to get java to comply with ICCCM.

Also, setting _NET_WM_NAME  to "LG3D" is to get Java to treat the WM as non-reparenting. This can also be accomplished on non-reparenting WMs by setting the environment variable `_JAVA_AWT_WM_NONREPARENTING=1`...

**Comment by wavexx** [comment] 2021-01-25 11:52
Thx @LordReg for the explaination.

After a quick test it seems that _JAVA_AWT_WM_NONREPARENTING=1 doesn't really affect the menu issue. I tried using wmname as well to set it to "LG3D" and in combination but the results are the same. So at least, this doesn't seem relevant to this specific issue.

So I tried setting "win->java = true" unconditionally around spectrwm.c:11311 and, indeed, this *does* fix menus consistently.

Looking again at xprop using jre15 I really don't see anything which we could use :(
Adding a quirk looks sensible, but also a PITA. I wonder what's the true impact of treating all windows as "retarded".. ?

**Comment by wavexx** [comment] 2021-01-25 11:59
@LordReg to be specific, it seems that the only relevant path required for java menus if the extra config_win() call in spectrwm.c:7852.

**Comment by LordReg** [comment] 2021-01-25 17:18
Regarding "LG3D" and `_JAVA_AWT_WM_NONREPARENTING=1`, those are to get java to treat the WM as non-reparenting. spectrwm is a reparenting WM and the default is `_JAVA_AWT_WM_NONREPARENTING=0', so that is unrelated to this issue.

Rather than setting "LG3D", `_NET_WM_NAME` can be overridden to the name of a reparenting window manager that java whitelists (e.g. "Metacity").  This method works but it's silly to misreport the name of the WM just to get java to follow ICCCM.

Therefore, always calling config_win() is the best option. Windows that are resized will receive a redundant ConfigureNotify, which is harmless.  This is better than playing the `_NET_WM_NAME` or java window detection game and requires no action by the user. Pushing the fix, so please verify it does the trick for you.

**Comment by wavexx** [comment] 2021-01-25 18:09
Looking at the diff, I've been running the exact same changes (down to the removal of the java field and the removal of the parent handling exception (which I figured was useless).

Rebuilding now with the official change. I'll report back in a week or so.
I truly hate java UIs in general, but I'm trying to give "ghidra" a try recently ;)

**Comment by wavexx** [comment] 2021-01-28 14:27
Looks properly fixed to me. I'm using a couple of java programs on a daily basis and now they're behaving properly (at least when running on openjdk15).

And all things considered, looks cleaner than the previous approach of detecting based on WM_CLASS.

**Comment by lemnos** [comment] 2021-06-20 02:41
I am still experiencing an issue with menus in Java programs. Specifically certain menus won't open in intellij and others are not properly positioned. I've tried messing with quirks to no avail, does anyone have this working on the latest version?

**Comment by LordReg** [comment] 2022-12-29 07:01
This should be fixed in master, closing.

**Closed by LordReg** 2022-12-29 07:01 UTC
Labels: bug
