### ISSUE TITLE
Crash on compiled 3.5.1 version.

### ISSUE THREAD

**Issue by ZaxonXP** [conformal/spectrwm#567] opened 2024-03-13 13:31 UTC
I got last release as zip, unpacked and recompiled with make (no errors) on Debian 12 bookworm. When I installed and restarted x11 I got this error:
```
spectrwm: Welcome to spectrwm V3.5.1 Build: 3.5.1
malloc(): corrupted top size
xinit: connection to X server lost
```
Is this issue known?

Kind regards,
Piotr

**Comment by LordReg** [comment] 2024-05-27 11:54
Was unable to reproduce the issue with defaults, so it may be conf dependent. Just pushed a possible fix on the release3.6 branch (f2ff20d5ea10bfe6bafd5d7792175c0bcdaaed23) please test.

**Comment by ZaxonXP** [comment] 2024-05-27 19:47
@LordReg: I compiled the new branch and managed to run it, but only on the clean config.
On my config it crashing. How can I find out what causing the crash? Is there any way to validate the config without disabling line by line and trying?

**Comment by ZaxonXP** [comment] 2024-05-27 20:35
On my config the crash generates such log:
```
spectrwm: Welcome to spectrwm V3.6.0 Build: f2ff20d5ea10bfe6bafd5d7792175c0bcdaaed23
spectrwm: sighdlr: child exit status: 1
malloc(): corrupted top size
```
Should I attach my config to this bug?

**Comment by LordReg** [comment] 2024-05-28 03:28
> Should I attach my config to this bug?

Please do

**Comment by ZaxonXP** [comment] 2024-05-28 05:46
Attached.
[spectrwm_configs.zip](https://github.com/conformal/spectrwm/files/15464487/spectrwm_configs.zip)

**Comment by LordReg** [comment] 2024-05-30 01:21
@ZaxonXP your config was helpful. Fixed on the release3.6 branch.

**Closed by LordReg** 2024-05-30 01:21 UTC

**Comment by ZaxonXP** [comment] 2024-06-04 13:23
Indeed. Now it compiles and works correctly. Many thanks!
